In [2]:
import pandas as pd

train_data = pd.read_csv("../../data/insurance/train.csv")
test_data = pd.read_csv("../../data/insurance/test.csv")

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  object
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  object
 5   population_density                58592 non-null  int64
 6   make                              58592 non-null  int64
 7   segment                           58592 non-null  object
 8   model                             58592 non-null  object
 9   fuel_type                         58592 non-null  object
 10  max_torque                        58592 non-null  object
 11  max_power                         58592 non-null  object
 12  engine_type                       58592 non-null  object
 13  airbags                           58592 non-null  int64
 14  is_esc                            58592 non-null  object
 15  is_adjustable_steering            58592 non-null  object
 16  is_tpms                           58592 non-null  object
 17  is_parking_sensors                58592 non-null  object
 18  is_parking_camera                 58592 non-null  object
 19  rear_brakes_type                  58592 non-null  object
 20  displacement                      58592 non-null  int64
 21  cylinder                          58592 non-null  int64
 22  transmission_type                 58592 non-null  object
 23  gear_box                          58592 non-null  int64
 24  steering_type                     58592 non-null  object
 25  turning_radius                    58592 non-null  float64
 26  length                            58592 non-null  int64
 27  width                             58592 non-null  int64
 28  height                            58592 non-null  int64
 29  gross_weight                      58592 non-null  int64
 30  is_front_fog_lights               58592 non-null  object
 31  is_rear_window_wiper              58592 non-null  object
 32  is_rear_window_washer             58592 non-null  object
 33  is_rear_window_defogger           58592 non-null  object
 34  is_brake_assist                   58592 non-null  object
 35  is_power_door_locks               58592 non-null  object
 36  is_central_locking                58592 non-null  object
 37  is_power_steering                 58592 non-null  object
 38  is_driver_seat_height_adjustable  58592 non-null  object
 39  is_day_night_rear_view_mirror     58592 non-null  object
 40  is_ecw                            58592 non-null  object
 41  is_speed_alert                    58592 non-null  object
 42  ncap_rating                       58592 non-null  int64
 43  is_claim                          58592 non-null  int64
dtypes: float64(4), int64(12), object(28)
memory usage: 19.7+ MB

In [4]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39063 entries, 0 to 39062
Data columns (total 43 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         39063 non-null  object
 1   policy_tenure                     39063 non-null  float64
 2   age_of_car                        39063 non-null  float64
 3   age_of_policyholder               39063 non-null  float64
 4   area_cluster                      39063 non-null  object
 5   population_density                39063 non-null  int64
 6   make                              39063 non-null  int64
 7   segment                           39063 non-null  object
 8   model                             39063 non-null  object
 9   fuel_type                         39063 non-null  object
 10  max_torque                        39063 non-null  object
 11  max_power                         39063 non-null  object
 12  engine_type                       39063 non-null  object
 13  airbags                           39063 non-null  int64
 14  is_esc                            39063 non-null  object
 15  is_adjustable_steering            39063 non-null  object
 16  is_tpms                           39063 non-null  object
 17  is_parking_sensors                39063 non-null  object
 18  is_parking_camera                 39063 non-null  object
 19  rear_brakes_type                  39063 non-null  object
 20  displacement                      39063 non-null  int64
 21  cylinder                          39063 non-null  int64
 22  transmission_type                 39063 non-null  object
 23  gear_box                          39063 non-null  int64
 24  steering_type                     39063 non-null  object
 25  turning_radius                    39063 non-null  float64
 26  length                            39063 non-null  int64
 27  width                             39063 non-null  int64
 28  height                            39063 non-null  int64
 29  gross_weight                      39063 non-null  int64
 30  is_front_fog_lights               39063 non-null  object
 31  is_rear_window_wiper              39063 non-null  object
 32  is_rear_window_washer             39063 non-null  object
 33  is_rear_window_defogger           39063 non-null  object
 34  is_brake_assist                   39063 non-null  object
 35  is_power_door_locks               39063 non-null  object
 36  is_central_locking                39063 non-null  object
 37  is_power_steering                 39063 non-null  object
 38  is_driver_seat_height_adjustable  39063 non-null  object
 39  is_day_night_rear_view_mirror     39063 non-null  object
 40  is_ecw                            39063 non-null  object
 41  is_speed_alert                    39063 non-null  object
 42  ncap_rating                       39063 non-null  int64
dtypes: float64(4), int64(11), object(28)
memory usage: 12.8+ MB

In [6]:
data = pd.concat([train_data, test_data])

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97655 entries, 0 to 39062
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         97655 non-null  object
 1   policy_tenure                     97655 non-null  float64
 2   age_of_car                        97655 non-null  float64
 3   age_of_policyholder               97655 non-null  float64
 4   area_cluster                      97655 non-null  object
 5   population_density                97655 non-null  int64
 6   make                              97655 non-null  int64
 7   segment                           97655 non-null  object
 8   model                             97655 non-null  object
 9   fuel_type                         97655 non-null  object
 10  max_torque                        97655 non-null  object
 11  max_power                         97655 non-null  object
 12  engine_type                       97655 non-null  object
 13  airbags                           97655 non-null  int64
 14  is_esc                            97655 non-null  object
 15  is_adjustable_steering            97655 non-null  object
 16  is_tpms                           97655 non-null  object
 17  is_parking_sensors                97655 non-null  object
 18  is_parking_camera                 97655 non-null  object
 19  rear_brakes_type                  97655 non-null  object
 20  displacement                      97655 non-null  int64
 21  cylinder                          97655 non-null  int64
 22  transmission_type                 97655 non-null  object
 23  gear_box                          97655 non-null  int64
 24  steering_type                     97655 non-null  object
 25  turning_radius                    97655 non-null  float64
 26  length                            97655 non-null  int64
 27  width                             97655 non-null  int64
 28  height                            97655 non-null  int64
 29  gross_weight                      97655 non-null  int64
 30  is_front_fog_lights               97655 non-null  object
 31  is_rear_window_wiper              97655 non-null  object
 32  is_rear_window_washer             97655 non-null  object
 33  is_rear_window_defogger           97655 non-null  object
 34  is_brake_assist                   97655 non-null  object
 35  is_power_door_locks               97655 non-null  object
 36  is_central_locking                97655 non-null  object
 37  is_power_steering                 97655 non-null  object
 38  is_driver_seat_height_adjustable  97655 non-null  object
 39  is_day_night_rear_view_mirror     97655 non-null  object
 40  is_ecw                            97655 non-null  object
 41  is_speed_alert                    97655 non-null  object
 42  ncap_rating                       97655 non-null  int64
 43  is_claim                          58592 non-null  float64
dtypes: float64(5), int64(11), object(28)
memory usage: 33.5+ MB

In [8]:
data.head()

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0.0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0.0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0.0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0.0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0.0

## EDA

In [9]:
# remove id column
data.drop("policy_id",axis=1,inplace=True)

In [10]:
data.shape

(97655, 43)

In [11]:
data.columns

Index(['policy_tenure', 'age_of_car', 'age_of_policyholder', 'area_cluster',
       'population_density', 'make', 'segment', 'model', 'fuel_type',
       'max_torque', 'max_power', 'engine_type', 'airbags', 'is_esc',
       'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'displacement', 'cylinder',
       'transmission_type', 'gear_box', 'steering_type', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'is_front_fog_lights',
       'is_rear_window_wiper', 'is_rear_window_washer',
       'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks',
       'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert', 'ncap_rating', 'is_claim'],
      dtype='object')

In [13]:
data.dtypes

policy_tenure                       float64
age_of_car                          float64
age_of_policyholder                 float64
area_cluster                         object
population_density                    int64
make                                  int64
segment                              object
model                                object
fuel_type                            object
max_torque                           object
max_power                            object
engine_type                          object
airbags                               int64
is_esc                               object
is_adjustable_steering               object
is_tpms                              object
is_parking_sensors                   object
is_parking_camera                    object
rear_brakes_type                     object
displacement                          int64
cylinder                              int64
transmission_type                    object
gear_box                              int64
steering_type                        object
turning_radius                      float64
length                                int64
width                                 int64
height                                int64
gross_weight                          int64
is_front_fog_lights                  object
is_rear_window_wiper                 object
is_rear_window_washer                object
is_rear_window_defogger              object
is_brake_assist                      object
is_power_door_locks                  object
is_central_locking                   object
is_power_steering                    object
is_driver_seat_height_adjustable     object
is_day_night_rear_view_mirror        object
is_ecw                               object
is_speed_alert                       object
ncap_rating                           int64
is_claim                            float64
dtype: object

In [18]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
policy_tenure,97655.0,0.611269,0.414494,0.002735,0.209729,0.573891,1.039740,1.396641
age_of_car,97655.0,0.069508,0.056774,0.000000,0.020000,0.060000,0.110000,1.000000
age_of_policyholder,97655.0,0.469287,0.122560,0.288462,0.375000,0.451923,0.548077,1.000000
population_density,97655.0,18822.608090,17656.792570,290.000000,6112.000000,8794.000000,27003.000000,73430.000000
make,97655.0,1.763586,1.135832,1.000000,1.000000,1.000000,3.000000,5.000000
airbags,97655.0,3.138109,1.831993,1.000000,2.000000,2.000000,6.000000,6.000000
displacement,97655.0,1161.655829,266.560176,796.000000,796.000000,1197.000000,1493.000000,1498.000000
cylinder,97655.0,3.624423,0.484274,3.000000,3.000000,4.000000,4.000000,4.000000
gear_box,97655.0,5.245579,0.430432,5.000000,5.000000,5.000000,5.000000,6.000000
turning_radius,97655.0,4.853024,0.228059,4.500000,4.600000,4.800000,5.000000,5.200000
length,97655.0,3850.017715,311.745860,3445.000000,3445.000000,3845.000000,3995.000000,4300.000000
width,97655.0,1672.050187,112.042508,1475.000000,1515.000000,1735.000000,1755.000000,1811.000000
height,97655.0,1553.214500,79.385788,1475.000000,1475.000000,1530.000000,1635.000000,1825.000000
gross_weight,97655.0,1384.966750,212.543007,1051.000000,1185.000000,1335.000000,1510.000000,1720.000000
ncap_rating,97655.0,1.759664,1.388415,0.000000,0.000000,2.000000,3.000000,5.000000
is_claim,58592.0,0.063968,0.244698,0.000000,0.000000,0.000000,0.000000,1.000000

In [20]:
data.groupby("cylinder")[["is_claim", "displacement"]].describe().T

cylinder                       3             4
is_claim     count  21857.000000  36735.000000
             mean       0.059706      0.066503
             std        0.236947      0.249163
             min        0.000000      0.000000
             25%        0.000000      0.000000
             50%        0.000000      0.000000
             75%        0.000000      0.000000
             max        1.000000      1.000000
displacement count  36677.000000  60978.000000
             mean     863.769992   1340.827971
             std      102.187276    148.442266
             min      796.000000   1196.000000
             25%      796.000000   1197.000000
             50%      796.000000   1197.000000
             75%      998.000000   1493.000000
             max     1199.000000   1498.000000

In [21]:
data.select_dtypes("int").describe().T

,count,mean,std,min,25%,50%,75%,max
population_density,97655.0,18822.608090,17656.792570,290.0,6112.0,8794.0,27003.0,73430.0
make,97655.0,1.763586,1.135832,1.0,1.0,1.0,3.0,5.0
airbags,97655.0,3.138109,1.831993,1.0,2.0,2.0,6.0,6.0
displacement,97655.0,1161.655829,266.560176,796.0,796.0,1197.0,1493.0,1498.0
cylinder,97655.0,3.624423,0.484274,3.0,3.0,4.0,4.0,4.0
gear_box,97655.0,5.245579,0.430432,5.0,5.0,5.0,5.0,6.0
length,97655.0,3850.017715,311.745860,3445.0,3445.0,3845.0,3995.0,4300.0
width,97655.0,1672.050187,112.042508,1475.0,1515.0,1735.0,1755.0,1811.0
height,97655.0,1553.214500,79.385788,1475.0,1475.0,1530.0,1635.0,1825.0
gross_weight,97655.0,1384.966750,212.543007,1051.0,1185.0,1335.0,1510.0,1720.0
ncap_rating,97655.0,1.759664,1.388415,0.0,0.0,2.0,3.0,5.0

In [22]:
data.to_csv("../../data/insurance/claims_data.csv", index=False)